(Background on this error at: https://sqlalche.me/e/20/f405) [in /app/photovault/routes/upload.py:186]
ERROR:photovault.routes.upload:Database error for img133_jpg.rf.41e7284bb86f9c9b7b49519dca16b864.jpg: (psycopg2.errors.UndefinedColumn) column "file_path" of relation "photo" does not exist
LINE 1: INSERT INTO photo (filename, original_name, file_path, thumb...
                                                    ^
[SQL: INSERT INTO photo (filename, original_name, file_path, thumbnail_path, file_size, width, height, mime_type, upload_source, created_at, updated_at, user_id, album_id, photo_date, date_text, date_circa, location_text, occasion, condition, photo_source, back_text, needs_restoration, auto_enhanced, processing_notes, edited_filename, paired_photo_id, is_back_side) VALUES (%(filename)s, %(original_name)s, %(file_path)s, %(thumbnail_path)s, %(file_size)s, %(width)s, %(height)s, %(mime_type)s, %(upload_source)s, %(created_at)s, %(updated_at)s, %(user_id)s, %(album_id)s, %(photo_date)s, %(date_text)s, %(date_circa)s, %(location_text)s, %(occasion)s, %(condition)s, %(photo_source)s, %(back_text)s, %(needs_restoration)s, %(auto_enhanced)s, %(processing_notes)s, %(edited_filename)s, %(paired_photo_id)s, %(is_back_side)s) RETURNING photo.id]
[parameters: {'filename': 'be3d8c96.jpg', 'original_name': 'hamka_img133_jpg.rf.41e7284bb86f9c9b7b49519dca16b864.jpg', 'file_path': '/app/photovault/uploads/1/be3d8c96.jpg', 'thumbnail_path': '/app/photovault/uploads/1/be3d8c96_thumb.jpg', 'file_size': 47392, 'width': 512, 'height': 512, 'mime_type': 'image/jpeg', 'upload_source': 'file', 'created_at': datetime.datetime(2025, 9, 22, 19, 54, 21, 754534), 'updated_at': datetime.datetime(2025, 9, 22, 19, 54, 21, 754540), 'user_id': 1, 'album_id': None, 'photo_date': None, 'date_text': None, 'date_circa': False, 'location_text': None, 'occasion': None, 'condition': None, 'photo_source': None, 'back_text': None, 'needs_restoration': False, 'auto_enhanced': False, 'processing_notes': None, 'edited_filename': None, 'paired_photo_id': None, 'is_back_side': False}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-09-22 19:54:21,756 INFO: Deleted file: /app/photovault/uploads/1/be3d8c96.jpg [in /app/photovault/utils/file_handler.py:237]
[2025-09-22 19:54:21,756] INFO in file_handler: Deleted file: /app/photovault/uploads/1/be3d8c96.jpg
INFO:photovault.utils.file_handler:Deleted file: /app/photovault/uploads/1/be3d8c96.jpg
[2025-09-22 19:54:21,756] INFO in file_handler: Deleted file: /app/photovault/uploads/1/be3d8c96_thumb.jpg
2025-09-22 19:54:21,756 INFO: Deleted file: /app/photovault/uploads/1/be3d8c96_thumb.jpg [in /app/photovault/utils/file_handler.py:237]
INFO:photovault.utils.file_handler:Deleted file: /app/photovault/uploads/1/be3d8c96_thumb.jpg